name: activity_recognition_alt
description: Activity recognition plugin for Android and iOS using the native APIs with updated Kotlin version to 1.2.51, forked from https://github.com/Morosko/flutter_activity_recognition
  - ActivityRecognitionClient on Android, CoreMotion on iOS.
version: 0.1.6
author: Tony Wei <tonywei92@gmail.com>
homepage: https://github.com/tonywei92/flutter_activity_recognition

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=2.0.0-dev.28.0 <3.0.0"

flutter:
  plugin:
    androidPackage: at.resiverbindet.activityrecognition
    pluginClass: ActivityRecognitionPlugin
