name: activity_recognition
description: Activity recognition plugin for Android and iOS using the native APIs
  - ActivityRecognitionClient on Android, CoreMotion on iOS.
version: 0.1.2
author: Daniel Morawetz <development@resi-verbindet.at>
homepage: https://github.com/Morosko/flutter_activity_recognition

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=2.0.0-dev.28.0 <3.0.0"

flutter:
  plugin:
    androidPackage: at.resiverbindet.activityrecognition
    pluginClass: ActivityRecognitionPlugin
